version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker_compose/Dockerfile.dev
    command: /usr/dev.sh
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    # environment:
      # DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos